class _BotCommands:
    def __init__(self):
        self.StartCommand = 'stt1'
        self.MirrorCommand = 'mir1'
        self.UnzipMirrorCommand = 'unzipmir1'
        self.TarMirrorCommand = 'tarmir1'
        self.CancelMirror = 'can1'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'search1'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth1'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help1'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'ooklatest1'
        self.CloneCommand = 'clone1'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.ConfigMenuCommand = 'config1'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
